#!/usr/bin/env python3
"""Regenerates icons/ and src/generated.rs from a Lucide checkout.

Usage: python crates/z-icons/generate.py <path-to-lucide-repo>
"""
import re
import sys
from pathlib import Path

root = Path(__file__).parent
if len(sys.argv) != 2:
    sys.exit(__doc__)
src = Path(sys.argv[1]) / "icons"
sources = sorted(src.glob("*.svg"), key=lambda svg: svg.stem)
if not sources:
    sys.exit(f"No SVG icons found in {src}")
out = root / "icons"
out.mkdir(exist_ok=True)

lines = ["// @generated by generate.py from Lucide. Do not edit.\n", "use crate::Icon;\n\n"]
seen = {}
for svg in sources:
    name = svg.stem
    ident = re.sub(r"[^A-Za-z0-9]", "_", name).upper()
    if ident[0].isdigit():
        ident = "_" + ident
    assert ident not in seen, f"{name} collides with {seen[ident]}"
    seen[ident] = name
    text = re.sub(r"\s*\n\s*", " ", svg.read_text(encoding="utf-8").strip())
    text = text.replace('"currentColor"', '"#fff"').replace(" >", ">")
    (out / svg.name).write_text(text, encoding="utf-8", newline="\n")
    lines.append(
        f'/// Lucide `{name}` icon.\n'
        f'pub static {ident}: Icon = Icon::bundled("{name}", include_str!("../icons/{svg.name}"));\n'
    )
for stale in out.glob("*.svg"):
    if stale.stem not in seen.values():
        stale.unlink()
lines.append('\n#[cfg(feature = "catalog")]\n')
lines.append('pub(crate) static ALL: &[&Icon] = &[\n')
lines.extend(f'    &{ident},\n' for ident in seen)
lines.append('];\n')
(root / "src" / "generated.rs").write_text("".join(lines), encoding="utf-8", newline="\n")
print(len(seen), "icons")
