#!/usr/bin/env python3
"""Regenerates icons/ and src/generated.rs from a Lucide checkout.

Usage: python crates/z-icons/generate.py <path-to-lucide-repo>
"""
import re
import shutil
import sys
from pathlib import Path

root = Path(__file__).parent
src = Path(sys.argv[1]) / "icons"
out = root / "icons"
shutil.rmtree(out, ignore_errors=True)
out.mkdir()

lines = ["// @generated by generate.py from Lucide. Do not edit.\n", "use crate::Icon;\n\n"]
seen = {}
for svg in sorted(src.glob("*.svg")):
    name = svg.stem
    ident = re.sub(r"[^A-Za-z0-9]", "_", name).upper()
    if ident[0].isdigit():
        ident = "_" + ident
    assert ident not in seen, f"{name} collides with {seen[ident]}"
    seen[ident] = name
    text = re.sub(r"\s*\n\s*", " ", svg.read_text(encoding="utf-8").strip())
    text = text.replace('"currentColor"', '"#fff"').replace(" >", ">")
    (out / svg.name).write_text(text, encoding="utf-8", newline="\n")
    lines.append(
        f'pub static {ident}: Icon = Icon::new("{name}", include_bytes!("../icons/{svg.name}"));\n'
    )
(root / "src" / "generated.rs").write_text("".join(lines), encoding="utf-8", newline="\n")
print(len(seen), "icons")
